const express=require("express")
const router=express.Router()
const {listProducts,getProduct,getShopProducts, listProductsUser}=require("../Controllers/productController")
const{getCategoriesUser}=require("../Controllers/categoryController")
const {getCart,addItem,updateItemQty,removeItem,clearCart}=require("../Controllers/cartController")
const{createOrder, getMyOrders, getOrderDetails,createEnquiry}=require("../Controllers/orderController")
const {protect,isAdmin}=require("../Middleware/authMiddleware")
const { getAddresses, updateAddress, createAddress, setDefaultAddress, deleteAddress } = require("../Controllers/addressController")

router.get("/products",protect,listProducts)
router.get("/products-user",protect,listProductsUser)
router.get("/products/:slug",protect,getProduct)
router.get("/categories",protect,getCategoriesUser)
router.get("/products-shop",protect,getShopProducts)
router.get("/cart",protect,getCart)
router.post("/cart/items",protect,addItem)
router.patch("/cart/items/:itemId",protect,updateItemQty)
router.delete("/cart/items/:itemId",protect,removeItem)
router.delete("/cart",protect,clearCart)
router.post("/orders",protect,createOrder)
router.get("/addresses",protect,getAddresses)
router.post("/addresses",protect,createAddress)
router.put("/addresses/:id",protect,updateAddress)
router.patch("/addresses/:id/default",protect,setDefaultAddress)
router.delete("/addresses/:id",protect,deleteAddress)
router.get("/orders/my-orders",protect,getMyOrders)
router.get("/orders/:id",protect,getOrderDetails)
router.post("/enquiry",protect, createEnquiry);


module.exports=router